TOP_TEN_STOCK = [{'Rank': 1, 'Exchange': 'Nasdaq - US', 'Market_Cap': 34998500.0, 'Symbol': 'NASDAQ', 'Index': '^IXIC'}, 
                 {'Rank': 2, 'Exchange': 'NYSE', 'Market_Cap': 30964048.55, 'Symbol': 'NYSE', 'Index': '^GSPC'}, 
                 {'Rank': 3, 'Exchange': 'Shanghai Stock Exchange', 'Market_Cap': 10185996.7, 'Symbol': 'SSE', 'Index': '000001.SS'}, 
                 {'Rank': 4, 'Exchange': 'Euronext', 'Market_Cap': 8678440.56, 'Symbol': 'EURONEXT', 'Index': '^N100'}, 
                 {'Rank': 5, 'Exchange': 'Japan Exchange Group', 'Market_Cap': 7643430.36, 'Symbol': 'JPX', 'Index': '^N225'}, 
                 {'Rank': 6, 'Exchange': 'Shenzhen Stock Exchange', 'Market_Cap': 6362336.18, 'Symbol': 'SZSE', 'Index': '399001.SZ'}, 
                 {'Rank': 7, 'Exchange': 'Hong Kong Exchanges and Clearing', 'Market_Cap': 5859852.86, 'Symbol': 'HKEX', 'Index': '^HSI'}, 
                 {'Rank': 8, 'Exchange': 'TMX Group', 'Market_Cap': 4710982.4, 'Symbol': 'TSX', 'Index': '^GSPTSE'}, 
                 {'Rank': 9, 'Exchange': 'National Stock Exchange of India', 'Market_Cap': 4336638.96, 'Symbol': 'NSE', 'Index': '^NSEI'}, 
                 {'Rank': 10, 'Exchange': 'BSE India Limited', 'Market_Cap': 4334396.98, 'Symbol': 'BSE', 'Index': '^BSESN'}]